### ISSUE TITLE
Generated pages (sitemap.xml and robots.txt) get wrapped in html

### ISSUE THREAD

**Issue by cargocultprogramming** [riboseinc/jekyll-external-links#7]
When using jekyll-external-links with jekyll-sitemap, the files produced by jekyll-sitemap (sitemap.xml and robots.txt) will be wrapped in html:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<?xml version="1.0" encoding="UTF-8"?><html><body>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemalocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
...
actual sitemap goes here
...
</body></html>
```

Deactivating jekyll-external-links in the Gemfile will restore the original behaviour of jekyll-sitemaps to generate the files without extra markup.

Settings for jekyll-external-links in _conf.yml:

```
external_links:
  selector: 'main a'
  marker_html: '<span class="fe fe-external-link external-link"></span>'
```

**Comment by axb21** [comment]
The Atom feed created by `jekyll-feed` is also wrapped in HTML.

Is there any known fix or workaround for this? It's really annoying. *Installing* this plugin alone causes this behavior, even if it is not turned on in `_config.yml`.

**Comment by axb21** [comment]
It looks like there's a pull request waiting that fixes this issue: https://github.com/riboseinc/jekyll-external-links/pull/5

@strogonoff et al., are you not maintaining this plugin anymore?

**Comment by axb21** [comment]
I just made the change indicated in the pull request locally and verified that it fixes the issues with feed.xml, sitemap.xml, and robots.txt. So, @cargocultprogramming , that's a workaround that might work for you until this PR is merged.

What I did was clone the repo, cd into it, change the version number to "1.0.2" in `jekyll-external-links.gemspec`, `gem build jekyll-external-links.gemspec`, and then finally `gem install ./jekyll-external-links-1.0.2.gem` to get the new gem installed locally. After that you can peg the version number of `jekyll-external-links` to 1.0.2 in your site's `Gemfile`, run `bundle`, and you should be good to go.

**Comment by cargocultprogramming** [comment]
Thanks for the workaround @axb21 ! 

I ended up to include this fork (https://github.com/Rp70/jekyll-external-links) that addresses this issue. I included it directly in my gemfile instead of the original like so:

> gem 'jekyll-external-links', :git => 'https://github.com/Rp70/jekyll-external-links'

This will pull in the forked repo and install the gem from there. The fork works as advertised and doesn't touch any non-html files, which is the source of the error.

Unfortunately this is pretty stale and there is no active development or even maintenance that I'm aware of. On the other hand with the fork mentioned above my web page generation works fine.

**Comment by axb21** [comment]
Thanks @cargocultprogramming , that's a more elegant workaround than mine!

I think it's a big problem with these open source projects on github. Whoever is maintaining them stops for whatever reason (which is fair enough of course; life happens), but then the project goes stale and there's no obvious way for random people like us to commit changes. I know you don't want to have any random person committing code and pushing it out as an "official" Ruby gem, but there has to be a reasonable middle ground?

**Comment by ronaldtse** [comment]
@axb21 @cargocultprogramming luckily we’re still reading these messages here and we just need to get the fix verified to make a new release. Thank you for alerting this to our attention!

@strogonoff @CAMOBAP can you please help here? Thanks!

**Comment by strogonoff** [comment]
The fix in #5 had been merged and released in https://github.com/riboseinc/jekyll-external-links/releases/tag/v1.0.2.

Post-mortem indicates two causes:

1. The original condition excluded files marked by Jekyll as static assets. However, not being a static asset does not necessarily guarantee it’s an HTML file, so we ended up with XML file contents being passed through `process_content()` function.
2. The `process_content()` function passes *all* given `content` through Nokogiri—even if it happens to be XML and external links never occur in it. And `Nokogiri::HTML`, when given XML, would prepend an HTML header to the contents.

The fix as implemented addresses (1) by also excluding any file without `.html` extension. I think this is fair, originally I thought we shouldn’t restrict this to HTML files only but an abstract flexible solution that elegantly handles non-HTML files would probably be overly complex (and Jekyll itself seems to prefer focusing on most common use cases over being infinitely flexible) so I take that back.

There are some opportunities for improving the `process_content()` function implementation:

- It could check whether given string contains HTML, though we should be mindful of performance when doing so.
- It could check whether specified external link selectors ever appear in given contents. If not, the function should do nothing and return contents as is: in addition to avoiding this bug, it could actually benefit performance in cases where external links don’t appear on every page.

**Comment by strogonoff** [comment]
One way to improve on this fix could be to check against [`HTML_EXTENSIONS` list provided by Jekyll](https://www.rubydoc.info/github/jekyll/jekyll/Jekyll/Page#HTML_EXTENSIONS-constant) instead of just hard-coded `.html` string.

**Comment by ronaldtse** [comment]
Thank you @strogonoff! 

Thank you @cargocultprogramming @axb21 for reporting and contributing!

**Comment by axb21** [comment]
Thanks for fixing this! It's great there's life in this plugin, since it's very handy!

**Comment by cargocultprogramming** [comment]
Great, thanks for the fix! Can confirm that it's only operating on html files now. Great plugin!
